services:
  - type: web
    name: doronin-website
    env: static
    buildCommand: echo "No build required for static site"
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 